name: Security Scan
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }
      - run: pip install bandit pip-audit
      - run: bandit -r src/ -ll
<<<<<<< Updated upstream
      - run: pip-audit -r requirements.txt --ignore-vuln PYSEC-2026-1325 --ignore-vuln PYSEC-2026-2263 --ignore-vuln PYSEC-2026-3457 --ignore-vuln PYSEC-2026-3456 --ignore-vuln PYSEC-2026-3455
=======
      - run: pip-audit -r requirements.txt
>>>>>>> Stashed changes
